# Generated by Django 6.0.3 on 2026-03-27 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to='subjects/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.category')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resources/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/')),
                ('description', models.TextField()),
                ('class_level', models.IntegerField(blank=True, choices=[(1, '1-sinf'), (2, '2-sinf'), (3, '3-sinf'), (4, '4-sinf'), (5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf'), (10, '10-sinf'), (11, '11-sinf')], null=True)),
                ('language', models.CharField(choices=[('uz', 'O‘zbekcha'), ('ru', 'Ruscha'), ('en', 'Inglizcha')], default='uz', max_length=2)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject')),
            ],
        ),
    ]
